export const originalData = [
  {
    bookName: "The Great Gatsby",
    price: 12.99,
    rating: 4.5,
    category: "Fiction",
  },
  {
    bookName: "To Kill a Mockingbird",
    price: 14.95,
    rating: 4.8,
    category: "Fiction",
  },
  {
    bookName: "The Catcher in the Rye",
    price: 11.99,
    rating: 2.3,
    category: "Dystopian",
  },
  {
    bookName: "1984",
    price: 9.99,
    rating: 3.7,
    category: "Fiction",
  },
  {
    bookName: "Pride and Prejudice",
    price: 13.99,
    rating: 4.6,
    category: "Romance",
  },
  {
    bookName: "The Hobbit",
    price: 10.5,
    rating: 3.4,
    category: "Fantasy",
  },
  {
    bookName: "Sapiens: A Brief History of Humankind",
    price: 16.99,
    rating: 4.2,
    category: "Romance",
  },
  {
    bookName: "The Silent Patient",
    price: 15.25,
    rating: 2.6,
    category: "Mystery",
  },
  {
    bookName: "The Girl on the Train",
    price: 12.75,
    rating: 4.0,
    category: "Mystery",
  },
  {
    bookName: "Educated: A Memoir",
    price: 17.99,
    rating: 4.7,
    category: "Romance",
  },
  {
    bookName: "The Alchemist",
    price: 11.25,
    rating: 2.8,
    category: "SelfHelp",
  },
  {
    bookName: "The Road",
    price: 14.5,
    rating: 1.1,
    category: "Dystopian",
  },
  {
    bookName: "The Subtle Art",
    price: 13.99,
    rating: 3.3,
    category: "SelfHelp",
  },
  {
    bookName: "Dune",
    price: 18.95,
    rating: 4.5,
    category: "ScienceFiction",
  },
  {
    bookName: "Becoming",
    price: 16.75,
    rating: 4.8,
    category: "Biography",
  },
  {
    bookName: "Harry Potter",
    price: 9.99,
    rating: 4.7,
    category: "Fantasy",
  },
  {
    bookName: "Gone Girl",
    price: 12.25,
    rating: 2.2,
    category: "Mystery",
  },
  {
    bookName: "The Martian",
    price: 14.99,
    rating: 3.4,
    category: "ScienceFiction",
  },
  {
    bookName: "Life",
    price: 15.5,
    rating: 4.6,
    category: "Romance",
  },
  {
    bookName: "Games",
    price: 10.99,
    rating: 2.3,
    category: "Fantasy",
  },
];
